apiVersion: v1
kind: Service
metadata:
  name: drkiq
spec:
  selector:
    app: drkiq
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: drkiq
spec:
  selector:
    matchLabels:
      app: drkiq
  replicas: 1
  template:
    metadata:
      labels:
        app: drkiq
    spec:
      containers:
        - name: drkiq
          image: "mahaga50/drkiq:1"
          ports:
            - name: rails
              containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: DATABASE_URL
            - name: WORKER_PROCESSES
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: WORKER_PROCESSES
            - name: LISTEN_ON
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: LISTEN_ON
            - name: SECRET_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: SECRET_TOKEN
            - name: CACHE_URL
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: CACHE_URL
            - name: JOB_WORKER_URL
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: JOB_WORKER_URL
